// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessingService.Infrastructure.Persistence;

#nullable disable

namespace ProcessingService.Migrations
{
    [DbContext(typeof(ProcessingDbContext))]
    partial class ProcessingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProcessingService.Domain.Tanks.ProcessingTank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CapacityLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_processing_tanks_code");

                    b.ToTable("processing_tanks", (string)null);
                });

            modelBuilder.Entity("ProcessingService.Domain.Unloads.Unload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DispatchNoteReference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal>("QuantityLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("StoringTankId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UnloadDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UnloadedAtLocal")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UnloadedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchNoteReference")
                        .IsUnique()
                        .HasDatabaseName("ux_unloads_dispatch_note");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_unloads_reference");

                    b.HasIndex("StoringTankId");

                    b.HasIndex("UnloadDate")
                        .HasDatabaseName("ix_unloads_date");

                    b.ToTable("unloads", (string)null);
                });

            modelBuilder.Entity("ProcessingService.Domain.Unloads.Unload", b =>
                {
                    b.HasOne("ProcessingService.Domain.Tanks.ProcessingTank", "StoringTank")
                        .WithMany()
                        .HasForeignKey("StoringTankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StoringTank");
                });
#pragma warning restore 612, 618
        }
    }
}
