// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessingService.Infrastructure.Persistence;

#nullable disable

namespace ProcessingService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProcessingDbContext))]
    [Migration("20260915135458_AddMccDispatchTraceAndAllocation")]
    partial class AddMccDispatchTraceAndAllocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProcessingService.Domain.Entities.MccDispatchTrace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BowserRegistration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DispatchedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalQuantityLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalUnloadedKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_mcc_dispatch_traces_reference");

                    b.ToTable("mcc_dispatch_traces", (string)null);
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.ProcessingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BatchCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DispatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsTemperatureDeviation")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("QualityTestStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("StoringTankId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("TemperatureC")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BatchCode")
                        .IsUnique()
                        .HasDatabaseName("ux_processing_runs_batchcode");

                    b.HasIndex("DispatchNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_processing_runs_dispatch");

                    b.HasIndex("StoringTankId");

                    b.ToTable("processing_runs", (string)null);
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.ProcessingRunStoringAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("StoringTankId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StoringTankId");

                    b.HasIndex("ProcessingRunId", "StoringTankId")
                        .HasDatabaseName("ix_storing_alloc_run_tank");

                    b.ToTable("processing_run_storing_allocations", (string)null);
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.ProcessingStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("CultureAdded")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CultureAddedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("EndTemperatureC")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("EndTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeviation")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MixingTankId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MixingTankId");

                    b.HasIndex("ProcessingRunId");

                    b.ToTable("processing_stages", (string)null);
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.QualityPanel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AlcoholOutcomesJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AlcoholResult")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("ColourOk")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DispatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FailedParameter")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FailedValue")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("FatPercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsSmellConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTasteConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KqColour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Ph")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("RawLactometerReading")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("SmellOk")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Snf")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("TasteOk")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Ts")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("WaterPercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingRunId")
                        .IsUnique();

                    b.ToTable("quality_panels", (string)null);
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.Tank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CapacityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("RemainingKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_tanks_code");

                    b.ToTable("tanks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CapacityKg = 5000m,
                            Code = "ST-01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Kind = "Storing",
                            RemainingKg = 0m,
                            Status = "Active",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CapacityKg = 5000m,
                            Code = "ST-02",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Kind = "Storing",
                            RemainingKg = 0m,
                            Status = "Active",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CapacityKg = 5000m,
                            Code = "ST-03",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Kind = "Storing",
                            RemainingKg = 0m,
                            Status = "Active",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CapacityKg = 3000m,
                            Code = "MT-01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Kind = "Mixing",
                            RemainingKg = 0m,
                            Status = "Active",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CapacityKg = 3000m,
                            Code = "MT-02",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Kind = "Mixing",
                            RemainingKg = 0m,
                            Status = "Active",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CapacityKg = 3000m,
                            Code = "MT-03",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Kind = "Mixing",
                            RemainingKg = 0m,
                            Status = "Active",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        });
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.TankAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AllocatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BatchLetter")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("BatchNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("DestinationMixingTankId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("SourceStoringTankId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BatchCode")
                        .IsUnique()
                        .HasDatabaseName("ux_tank_allocations_batchcode");

                    b.HasIndex("DestinationMixingTankId");

                    b.HasIndex("ProcessingRunId");

                    b.HasIndex("SourceStoringTankId");

                    b.HasIndex("BatchNumber", "ProductType", "BatchLetter")
                        .IsUnique()
                        .HasDatabaseName("ux_tank_allocations_day_product_letter");

                    b.ToTable("tank_allocations", (string)null);
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.ProcessingRun", b =>
                {
                    b.HasOne("ProcessingService.Domain.Entities.Tank", "StoringTank")
                        .WithMany("ProcessingRuns")
                        .HasForeignKey("StoringTankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StoringTank");
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.ProcessingRunStoringAllocation", b =>
                {
                    b.HasOne("ProcessingService.Domain.Entities.ProcessingRun", "ProcessingRun")
                        .WithMany("StoringAllocations")
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessingService.Domain.Entities.Tank", "StoringTank")
                        .WithMany()
                        .HasForeignKey("StoringTankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessingRun");

                    b.Navigation("StoringTank");
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.ProcessingStage", b =>
                {
                    b.HasOne("ProcessingService.Domain.Entities.Tank", "MixingTank")
                        .WithMany("Stages")
                        .HasForeignKey("MixingTankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcessingService.Domain.Entities.ProcessingRun", "ProcessingRun")
                        .WithMany("Stages")
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixingTank");

                    b.Navigation("ProcessingRun");
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.QualityPanel", b =>
                {
                    b.HasOne("ProcessingService.Domain.Entities.ProcessingRun", "ProcessingRun")
                        .WithOne("QualityPanel")
                        .HasForeignKey("ProcessingService.Domain.Entities.QualityPanel", "ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingRun");
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.TankAllocation", b =>
                {
                    b.HasOne("ProcessingService.Domain.Entities.Tank", "DestinationMixingTank")
                        .WithMany("DestinationAllocations")
                        .HasForeignKey("DestinationMixingTankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcessingService.Domain.Entities.ProcessingRun", "ProcessingRun")
                        .WithMany("Allocations")
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessingService.Domain.Entities.Tank", "SourceStoringTank")
                        .WithMany("SourceAllocations")
                        .HasForeignKey("SourceStoringTankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationMixingTank");

                    b.Navigation("ProcessingRun");

                    b.Navigation("SourceStoringTank");
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.ProcessingRun", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("QualityPanel");

                    b.Navigation("Stages");

                    b.Navigation("StoringAllocations");
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.Tank", b =>
                {
                    b.Navigation("DestinationAllocations");

                    b.Navigation("ProcessingRuns");

                    b.Navigation("SourceAllocations");

                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
