#!/usr/bin/env bash
# Deploy the staging observability stack to the Kafka VM (SCRUM-111).
#
#   ./infra/observability/staging/deploy.sh <vm-fqdn> <service>=<app-service-host> [...]
#
# e.g.
#   ./infra/observability/staging/deploy.sh wonrich-kafka.southeastasia.cloudapp.azure.com \
#       quality-lab-service=wonrich-quality-lab-xxxx.southeastasia-01.azurewebsites.net \
#       processing-service=<processing app host>
#
# Each <service>=<host> becomes one HTTPS scrape job labelled service=<service>, environment=staging.
# Re-run it to add a service or pick up changed alerts or dashboards; Grafana's password and both
# data volumes are kept. Needs SSH access to the VM (the Kafka VM's admin user).
set -euo pipefail
cd "$(dirname "$0")/../../.."          # repository root

FQDN="${1:?usage: $0 <vm-fqdn> <service>=<host> [...]}"
shift
[ $# -gt 0 ] || { echo "give at least one <service>=<app-service-host>" >&2; exit 2; }
REMOTE="${SSH_USER:-azureuser}@$FQDN"

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
mkdir -p "$STAGE/prometheus" "$STAGE/grafana/provisioning" "$STAGE/grafana/dashboards"

# ── prometheus.yml, generated from the arguments ────────────────────────────────────────────────
{
  cat <<'EOF'
# Generated by infra/observability/staging/deploy.sh - do not edit on the VM, re-run the script.
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: prometheus
          environment: staging
EOF
  for pair in "$@"; do
    service="${pair%%=*}"
    host="${pair#*=}"
    host="${host#https://}"; host="${host%/}"
    [[ "$service" =~ ^[a-z0-9-]+$ && -n "$host" && "$pair" == *=* ]] \
      || { echo "bad argument '$pair' - expected <service>=<host>" >&2; exit 2; }
    cat <<EOF

  - job_name: $service
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['$host']
        labels:
          service: $service
          environment: staging
EOF
  done
} > "$STAGE/prometheus/prometheus.yml"

# ── shared files: the same alert rules and dashboard as local ───────────────────────────────────
cp infra/observability/prometheus/alerts.yml "$STAGE/prometheus/"
cp infra/observability/grafana/dashboards/*.json "$STAGE/grafana/dashboards/"
cp -r infra/observability/grafana/provisioning/dashboards "$STAGE/grafana/provisioning/"
cp -r infra/observability/staging/grafana/provisioning/datasources "$STAGE/grafana/provisioning/"
cp infra/observability/staging/docker-compose.yml "$STAGE/"

echo "== scrape targets"
grep -E "job_name|targets" "$STAGE/prometheus/prometheus.yml" | sed 's/^/   /'

echo "== copying to $REMOTE:~/observability"
ssh "$REMOTE" 'mkdir -p ~/observability'
scp -rq "$STAGE"/. "$REMOTE:~/observability/"

echo "== starting (Grafana password generated on first run only)"
ssh "$REMOTE" 'bash -s' <<'REMOTE_SCRIPT'
set -euo pipefail
cd ~/observability
if [ ! -f .env ]; then
  echo "GRAFANA_ADMIN_PASSWORD=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 24)" > .env
  chmod 600 .env
  echo "-- generated Grafana admin password"
fi
docker compose up -d
sleep 5
# Pick up config changes without losing data (Prometheus runs with --web.enable-lifecycle)
curl -fsS -X POST http://127.0.0.1:9090/-/reload >/dev/null && echo "-- Prometheus config reloaded"
docker compose ps
REMOTE_SCRIPT

cat <<DONE

== done. From your machine:

   ssh -N -L 13000:localhost:3000 -L 19090:localhost:9090 $REMOTE

   Grafana     http://localhost:13000   (admin / password: ssh $REMOTE 'cat ~/observability/.env')
   Prometheus  http://localhost:19090/targets
DONE
